name: Windows CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Install Scoop
        run: |
          iwr -useb get.scoop.sh -outfile 'install-scoop.ps1'
          ./install-scoop.ps1 -RunAsAdmin
          echo "~\scoop\shims" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\ProgramData\scoop\shims" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install LLVM
        run: |
          scoop install llvm
          echo "C:\Users\runneradmin\scoop\apps\llvm\current\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Get Clang Path
        run: (Get-Command clang-cl.exe).Source

      - name: Compile
        run: clang-cl -fsanitize=address -o main main.c

      - name: Run
        run: .\main.exe
